// <auto-generated />
using MessageHub.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MessageHub.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MessageHubDbContext))]
    [Migration("20260927141421_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("MessageHub.Core.Entities.ChannelContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ConnectedAccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("connected_account_id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("person_id");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_channel_contacts_email")
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_channel_contacts_person");

                    b.HasIndex("Phone")
                        .HasDatabaseName("ix_channel_contacts_phone")
                        .HasFilter("phone IS NOT NULL");

                    b.HasIndex("Username")
                        .HasDatabaseName("ix_channel_contacts_username")
                        .HasFilter("username IS NOT NULL");

                    b.HasIndex("ConnectedAccountId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_channel_contacts_account_external");

                    b.ToTable("channel_contacts");
                });

            modelBuilder.Entity("MessageHub.Core.Entities.ConnectedAccount.ConnectedAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT")
                        .HasColumnName("account_id");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("channel_type");

                    b.Property<long>("ConnectedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("connected_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("InitialHistoryDepth")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("initial_history_depth");

                    b.Property<long?>("LastSyncAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_sync_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<bool>("SyncEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sync_enabled");

                    b.HasKey("Id");

                    b.HasIndex("ChannelType", "AccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_connected_accounts_channel_account")
                        .HasFilter("account_id IS NOT NULL");

                    b.HasIndex("ChannelType", "Email")
                        .IsUnique()
                        .HasDatabaseName("ux_connected_accounts_channel_email")
                        .HasFilter("account_id IS NULL");

                    b.ToTable("connected_accounts");
                });

            modelBuilder.Entity("MessageHub.Core.Entities.Conversation.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long?>("AddedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("added_at");

                    b.Property<int?>("ChannelContactId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("channel_contact_id");

                    b.Property<int>("ConnectedAccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("connected_account_id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.Property<long?>("LastIncomingAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_incoming_at");

                    b.Property<long?>("LastMessageAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_message_at");

                    b.Property<string>("LastMessagePreview")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("last_message_preview");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<int>("UnreadCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unread_count");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ChannelContactId")
                        .HasDatabaseName("ix_conversations_channel_contact")
                        .HasFilter("channel_contact_id IS NOT NULL");

                    b.HasIndex("ConnectedAccountId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_conversations_account_external");

                    b.HasIndex("Status", "LastMessageAt")
                        .HasDatabaseName("ix_conversations_status_last_message");

                    b.ToTable("conversations");
                });

            modelBuilder.Entity("MessageHub.Core.Entities.ConversationParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("ChannelContactId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("channel_contact_id");

                    b.Property<int>("ConversationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("conversation_id");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.HasKey("Id");

                    b.HasIndex("ChannelContactId")
                        .HasDatabaseName("ix_conversation_participants_channel_contact")
                        .HasFilter("channel_contact_id IS NOT NULL");

                    b.HasIndex("ConversationId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_conversation_participants_conversation_external");

                    b.ToTable("conversation_participants");
                });

            modelBuilder.Entity("MessageHub.Core.Entities.MergeProposal.MergeProposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("confidence");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<int>("PersonHighId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("person_high_id");

                    b.Property<int>("PersonLowId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("person_low_id");

                    b.Property<string>("Reasons")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reasons");

                    b.Property<long?>("ResolvedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_merge_proposals_pending")
                        .HasFilter("status = 'Pending'");

                    b.HasIndex("PersonHighId")
                        .HasDatabaseName("ix_merge_proposals_high");

                    b.HasIndex("PersonLowId", "PersonHighId")
                        .IsUnique()
                        .HasDatabaseName("ux_merge_proposals_pair");

                    b.ToTable("merge_proposals");
                });

            modelBuilder.Entity("MessageHub.Core.Entities.Message.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AttachmentsInfo")
                        .HasColumnType("TEXT")
                        .HasColumnName("attachments_info");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("channel_type");

                    b.Property<string>("ClientMessageId")
                        .HasColumnType("TEXT")
                        .HasColumnName("client_message_id");

                    b.Property<int>("ConversationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("conversation_id");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("direction");

                    b.Property<long?>("EditedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("edited_at");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error");

                    b.Property<long?>("NextRetryAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("next_retry_at");

                    b.Property<long>("ReceivedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("received_at");

                    b.Property<long?>("RemoteDeletedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("remote_deleted_at");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<int?>("SenderParticipantId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sender_participant_id");

                    b.Property<long>("SentAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientMessageId")
                        .IsUnique()
                        .HasDatabaseName("ux_messages_client_message_id")
                        .HasFilter("client_message_id IS NOT NULL");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_messages_unread")
                        .HasFilter("is_read = 0");

                    b.HasIndex("NextRetryAt")
                        .HasDatabaseName("ix_messages_send_queue")
                        .HasFilter("status = 'Pending'");

                    b.HasIndex("SenderParticipantId");

                    b.HasIndex("ConversationId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_messages_conversation_external")
                        .HasFilter("external_id IS NOT NULL");

                    b.HasIndex("ConversationId", "SentAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_messages_conversation_sent_at");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("MessageHub.Core.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<int?>("PreferredChannelContactId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("preferred_channel_contact_id");

                    b.Property<string>("SearchName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("search_name");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_person_email")
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("Phone")
                        .HasDatabaseName("ix_person_phone")
                        .HasFilter("phone IS NOT NULL");

                    b.HasIndex("PreferredChannelContactId")
                        .IsUnique();

                    b.HasIndex("SearchName")
                        .HasDatabaseName("ix_person_search_name");

                    b.ToTable("person", (string)null);
                });

            modelBuilder.Entity("MessageHub.Core.Entities.RelationChangeLog.RelationChangeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("ChannelContactId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("channel_contact_id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("operation");

                    b.Property<int?>("PersonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("person_id");

                    b.Property<int?>("ProposalId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("proposal_id");

                    b.Property<int?>("RelatedPersonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("related_person_id");

                    b.Property<string>("Snapshot")
                        .HasColumnType("TEXT")
                        .HasColumnName("snapshot");

                    b.HasKey("Id");

                    b.HasIndex("RelatedPersonId")
                        .HasDatabaseName("ix_relation_change_logs_related_person")
                        .HasFilter("related_person_id IS NOT NULL");

                    b.HasIndex("PersonId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_relation_change_logs_person");

                    b.ToTable("relation_change_logs");
                });

            modelBuilder.Entity("MessageHub.Core.Entities.Settings.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("ConnectedAccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("connected_account_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("scope");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ux_settings_global_key")
                        .HasFilter("scope = 'Global'");

                    b.HasIndex("ConnectedAccountId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_settings_account_key")
                        .HasFilter("scope = 'Account'");

                    b.ToTable("settings");
                });

            modelBuilder.Entity("MessageHub.Core.Entities.SyncState.SyncState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ConnectedAccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("connected_account_id");

                    b.Property<int?>("ConversationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("conversation_id");

                    b.Property<string>("Cursor")
                        .HasColumnType("TEXT")
                        .HasColumnName("cursor");

                    b.Property<long?>("HistoryFrom")
                        .HasColumnType("INTEGER")
                        .HasColumnName("history_from");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<long?>("LastErrorAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_error_at");

                    b.Property<long?>("LastSuccessAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_success_at");

                    b.Property<long?>("NextRetryAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("next_retry_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("retry_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ConnectedAccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_sync_states_account_updates")
                        .HasFilter("kind = 'Updates'");

                    b.HasIndex("ConversationId")
                        .IsUnique()
                        .HasDatabaseName("ux_sync_states_conversation_history")
                        .HasFilter("kind = 'History'");

                    b.HasIndex("NextRetryAt")
                        .HasDatabaseName("ix_sync_states_next_retry")
                        .HasFilter("next_retry_at IS NOT NULL");

                    b.ToTable("sync_states");
                });

            modelBuilder.Entity("MessageHub.Core.Entities.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("KdfParams")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kdf_params");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("password_hash");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("password_salt");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("user_profiles");
                });

            modelBuilder.Entity("MessageHub.Core.Entities.ChannelContact", b =>
                {
                    b.HasOne("MessageHub.Core.Entities.ConnectedAccount.ConnectedAccount", "ConnectedAccount")
                        .WithMany("ChannelContacts")
                        .HasForeignKey("ConnectedAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MessageHub.Core.Entities.Person", "Person")
                        .WithMany("ChannelContacts")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConnectedAccount");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MessageHub.Core.Entities.Conversation.Conversation", b =>
                {
                    b.HasOne("MessageHub.Core.Entities.ChannelContact", null)
                        .WithMany()
                        .HasForeignKey("ChannelContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MessageHub.Core.Entities.ConnectedAccount.ConnectedAccount", null)
                        .WithMany()
                        .HasForeignKey("ConnectedAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MessageHub.Core.Entities.ConversationParticipant", b =>
                {
                    b.HasOne("MessageHub.Core.Entities.ChannelContact", null)
                        .WithMany()
                        .HasForeignKey("ChannelContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MessageHub.Core.Entities.Conversation.Conversation", null)
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MessageHub.Core.Entities.MergeProposal.MergeProposal", b =>
                {
                    b.HasOne("MessageHub.Core.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonHighId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MessageHub.Core.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonLowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MessageHub.Core.Entities.Message.Message", b =>
                {
                    b.HasOne("MessageHub.Core.Entities.Conversation.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MessageHub.Core.Entities.ConversationParticipant", null)
                        .WithMany()
                        .HasForeignKey("SenderParticipantId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MessageHub.Core.Entities.Person", b =>
                {
                    b.HasOne("MessageHub.Core.Entities.ChannelContact", null)
                        .WithOne()
                        .HasForeignKey("MessageHub.Core.Entities.Person", "PreferredChannelContactId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MessageHub.Core.Entities.Settings.Settings", b =>
                {
                    b.HasOne("MessageHub.Core.Entities.ConnectedAccount.ConnectedAccount", null)
                        .WithMany()
                        .HasForeignKey("ConnectedAccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MessageHub.Core.Entities.SyncState.SyncState", b =>
                {
                    b.HasOne("MessageHub.Core.Entities.ConnectedAccount.ConnectedAccount", null)
                        .WithMany()
                        .HasForeignKey("ConnectedAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MessageHub.Core.Entities.Conversation.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MessageHub.Core.Entities.ConnectedAccount.ConnectedAccount", b =>
                {
                    b.Navigation("ChannelContacts");
                });

            modelBuilder.Entity("MessageHub.Core.Entities.Conversation.Conversation", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("MessageHub.Core.Entities.Person", b =>
                {
                    b.Navigation("ChannelContacts");
                });
#pragma warning restore 612, 618
        }
    }
}
